# Server Configuration
server:
  port: 8080
  # Encoding
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  # Application Name
  application:
    name: moa-app
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://49.50.133.51:3306/moaapp_test?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#Swagger
springdoc:
  api-docs:
    enabled: true
    path: /swagger
# Logging
logging:
  level:
    root: info
    com.moa: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#Kakao API Key
kakao:
  api:
    key: 72c33e596f476c2ad70dea6ee9e24b46
  client:
    secret: hVLxNcM7R7ufPUNhFWPfdIGmtW3QLwcQ
  login:
    redirect:
      uri: http://49.50.133.51:8080/auth/kakao/callback
  logout:
    redirect:
      uri: http://49.50.133.51:8080/auth/kakao/logout